### ISSUE TITLE
"New Study" button redirects to login page for another instance

### ISSUE THREAD

**Issue by benthestatistician** [RTICWDT/evaluation-engine-website#1] opened 2016-11-29 19:37 UTC
Precis of problem:
1.  logged into staging instance
2. from Home screen, clicked "Start New Study"
3. Instead of starting a new study I'm sent to login page for _production_ instance, i.e. `http://reviewevaluationengine.org/Account/LogOn?ReturnUrl=%2fAnalysis%2fStep1`

Recognizing what was happening, I clicked the browser's back button, but the first couple of times this happened I confused by trying to log in again (being at the login page).  If real users get into this position they may get significantly spun around.

Having navigated back to the landing page, if I click "Start New Study" again I also get redirected to production instance login page. To get out of this loop I had to go to "My Library", then from there click the "Home" tab.  Once I did that I was able to start a new study. 

My setup: Chrome 54.0.2840.98 (64-bit), on OSX 10.11.6 .

**Comment by alexsmithRTI** [comment] 2017-03-14 16:21
Unable to reproduce, closing for now, but we can always reopen if the issue occurs again.

**Comment by benthestatistician** [comment] 2017-03-14 16:44
Problem is still there.   [Here's](https://bluejeans.com/s/6XfSc/) a Blue Jeans screen recording of me experiencing it.

**Comment by alexsmithRTI** [comment] 2017-03-14 16:56
I can fix this, but for now, use the staging login page to log in to staging. 

http://reviewevaluationengine.org/staging/Account/LogOn

This issue is that right now, you're going to http://reviewevaluationengine.org/staging and then are being redirected, but because of the way the staging and development URLS are handled, you need to have the trailing '/' after 'staging'.

**Comment by alexsmithRTI** [comment] 2017-03-14 18:00
All right,, NOW it's fixed. I tried what you did in your video and it works for me now. If you go to /staging, you will get redirected to /staging/ once you log in. This issue will go away entirely once we move to subdomains.

**Closed as completed by alexsmithRTI** 2017-03-14 18:00 UTC

**Comment by benthestatistician** [comment] 2017-03-14 19:03
thanks, @alexsmithRTI !  

I agree that the main issue here is whether an end user would experience the problem.  For future ref, I'd be happy to accept replies like "won't fix, just you be sure to add '`/`' to the end of '`staging`' in the URL" in lieu of a fix, if indeed it's something specific to my pseudo-developer workflow that's unlikely to hit a real user.
